plugins:
  - jekyll-remote-theme
remote_theme: ngzhio/jekyll-theme-hamilton
title: Eco's Homepage
description: You'll never walk alone.
author: YiKai Wang
email: eckowyk@gmail.com
avatar: ./icon.png
location: Wuhan
skin: sunset

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
logo: icon.png
